### ISSUE TITLE
sparsify_pointclouds

### ISSUE THREAD

**Issue by z393** [Mo-637/ROS2-KITTI-Preprocessing#1]
What is upper_threshold? If i want extract 32 beam lidar, what should i do? thanks

**Comment by moeara** [comment]
Hey, if you consider the outline of an HDL-64 -the lidar used to collect data in the KITTI dataset- you'll notice that the field of view is ~27 degrees and ranges from ~2 to -24.6 degrees, you'll also notice that it's divided into the 2 laser "blocks".

The VLP-16, on the other hand, has a FOV of 30 degrees that is equally distributed between 15 to -15 degrees.

So, to simulate data returned from a VLP-16, I essentially consider that I'm retrieving point clouds from a tilted VLP-16 lidar, and I take the tilt angle to be -11.45 degrees (which I consider the angle at which the centerline of the HDL-16 lies), this is as if you aligned the FOV centers of both sensors. 
Now to handle this programmatically, the vlp16_angles array signifies the angles of every laser beam in the VLP-16 LiDAR, so for every value in that array I correct the values to include the tilt angle and create a mask of all points that lie within a certain range from that specific laser beam. This range is defined by the upper and lower thresholds.

To simulate a 32 beam lidar (possibly a VLP-32) you would modify the vlp16_array to include 32 values instead of 16, where the values would signify the angles in degrees at which individual beams lie in the VLP-32 LiDAR sensor configuration.
